language: node_js
node_js:
  - "0.10"
install:
  - npm install
  - npm install -g grunt-cli
  - npm install -g bower
  - bower install
  - sudo easy_install Pygments
  - 'echo "{\"HOST\": \"anything\"}" > env.json'
